name: Execução dos testes unitários com Jest
on: 
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar o Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependências 
        run: npm install

      - name: Executar testes
        run: npm run test